/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Exhibitor = IDL.Record({
  'id' : IDL.Nat,
  'productCategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const StallBooking = IDL.Record({
  'id' : IDL.Nat,
  'stallType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([Event], [IDL.Nat], []),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getExhibitors' : IDL.Func([], [IDL.Vec(Exhibitor)], ['query']),
  'getNewsletterSignups' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStallBookings' : IDL.Func([], [IDL.Vec(StallBooking)], ['query']),
  'newsletterSignup' : IDL.Func([IDL.Text], [], []),
  'registerExhibitor' : IDL.Func([Exhibitor], [IDL.Nat], []),
  'submitStallBooking' : IDL.Func([StallBooking], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Exhibitor = IDL.Record({
    'id' : IDL.Nat,
    'productCategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const StallBooking = IDL.Record({
    'id' : IDL.Nat,
    'stallType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([Event], [IDL.Nat], []),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getExhibitors' : IDL.Func([], [IDL.Vec(Exhibitor)], ['query']),
    'getNewsletterSignups' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStallBookings' : IDL.Func([], [IDL.Vec(StallBooking)], ['query']),
    'newsletterSignup' : IDL.Func([IDL.Text], [], []),
    'registerExhibitor' : IDL.Func([Exhibitor], [IDL.Nat], []),
    'submitStallBooking' : IDL.Func([StallBooking], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };